### PR TITLE
Add Jason to AboutUs.md

### PR DESCRIPTION
**Pull request by jasonchristopher21**
Add Jason to the list of developers in AboutUs.md
- Add Jason's name, github and portfolio link in `AboutUs.md`
- Add Jason's profile photo (`jasonchristopher21.png`) to `images` directory
- Add Jason's Project Portfolio Page (PPP) under `docs/team`

### CODE REVIEW

**Comment by jasonchristopher21** [comment]
Thanks @autumn-sonata, I have added my PPP under `docs/team`

**Review by autumn-sonata — CHANGES_REQUESTED** [review]
Please add an additional newline at the EOF of `jasonchristopher21.md` for CI.

**Comment by jasonchristopher21** [comment]
Thanks @autumn-sonata, newline has been added to the EOF of `jasonchristopher21.md`

**Review by autumn-sonata — APPROVED** [review]
LGTM!

**Pull request merged**
